version: '3'
services:
  zoo1:
    image: zookeeper:3.7.0
    hostname: localhost
    container_name: zk
    user: zookeeper:zookeeper
    ports:
      - 21810:2181
  
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    hostname: localhost
    container_name: kk
    depends_on: 
      - zoo1
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka.local
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:21810"
      KAFKA_LOG_DIRS: "/kafka/kafka-logs"
      KAFKA_ADVERTISED_PORTS: 9092
      # KAFKA_CREATE_TOPICS: "arkuser:1:1, arkevent:1:1"
      # KAFKA_TRANSACTION_MAX_TIMEOUT_MS: "7200000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka-logs:/kafka/kafka-logs