version: '3.7'
services:
    minio:
        image: minio/minio:RELEASE.2021-04-22T15-44-28Z
        hostname: localhost
        container_name: minio
        ports:
            - 9000:9000
        volumes: 
            - ./data/data:/data
            # - ./data/config:/root/.minio
        command: server /data