version: '3.9'
services:
  redis:
    build:
      context: ./dir
      dockerfile: Dockerfile-alternate
      args:
        - buildno: 1
        - gitcommithash: cdc3b19
      cache_from:
        - alpine:latest
        - corp/web_app:3.14
      labels:
        com.example.description: "Accounting webapp"
        com.example.department: "Finance"
        com.example.label-with-empty-value: ""
      network: custom_network_1 # 可填入host, 填入none指在build过程中禁用网络
      shm_size: '1gb'
      target: prod
    image: webapp:tag # Dockerfile中ARG要在from之前
    container_name: rd
    cap_add:
      - ALL
    cap_drop:
      - NET_ADMIN
      - SYS_ADMIN
    cgroup_parent: m-executor-abcd
    configs: # 支持长短语法
      my_config:
        file: ./my_config.txt
      my_other_config:
        external: true
    command: redis-server /etc/redis.conf --appendonly yes
    credential_spec:
      file: my-credential-spec.json
    depends_on:
      - db
      - redis

    deploy:
      endpoint_mode: dnsrr
      labels:
        com.example.description: "This label will appear on the web service"
      mode: global
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      replicas: 2
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      rollback_config: order
      update_config:
        parallelism: 2
        delay: 10s
        order: stop-first
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    user: redis:redis
    hostname: localhost
    dns:
      - 8.8.8.8
      - 9.9.9.9
    dns_search:
      - dc1.example.com
      - dc2.example.com
    entrypoint: /code/entrypoint.sh
    env_file:
      - ./common.env
      - ./apps/web.env
      - /opt/runtime_opts.env
    environment:
      - RACK_ENV=development
      - SHOW=true
      - SESSION_SECRET
    expose:
      - "3000"
      - "8000"
    external_links:
      - redis_1
      - project_db_1:mysql
      - project_db_1:postgresql
    extra_hosts:
      - "somehost:162.242.195.82"
      - "otherhost:50.31.209.229"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    init: true
    isolation: default
    labels:
      - "com.example.description=Accounting webapp"
      - "com.example.department=Finance"
      - "com.example.label-with-empty-value"
    links:
      - "db"
      - "db:database"
      - "redis"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://192.168.0.42:123"
    network_mode: "bridge"
    networks:
      app_net:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10
    pid: "host"
    ports:
      - 6379:6379
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    profiles: ["frontend", "debug"]
    restart: "no"
    secrets:
      - source: my_secret
        target: redis_secret
        uid: '103'
        gid: '103'
        mode: 0440
    security_opt:
      - label:user:USER
      - label:role:ROLE
    stop_grace_period: 1s
    stop_signal: SIGUSR1
    sysctls:
      - net.core.somaxconn=1024
      - net.ipv4.tcp_syncookies=0
    tmpfs:
      - /run
      - /tmp
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    userns_mode: "host"
    volumes:
      - ./data:/data
      - ./redis.conf:/etc/redis.conf
      - ./redis.log:/log/redis.log


volumes:
  driver: foobar
  driver_opts:
    type: "nfs"
    o: "addr=10.40.0.199,nolock,soft,rw"
    device: ":/docker/example"
  data:
#    external: true # 3.4废除
    name: my-app-data
    labels:
      - "com.example.description=Database volume"
      - "com.example.department=IT/Ops"
      - "com.example.label-with-empty-value"

networks:
  web:
    driver: overlay
    driver_opts:
      foo: "bar"
      baz: 1
    attachable: true
#    enable_ipv6 # not supported in version 3
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
    internal: true
    labels:
      com.example.description: "Financial transaction network"
      com.example.department: "Finance"
      com.example.label-with-empty-value: ""
    name: web

configs:
  my_credentials_spec:
    file: ./my-credential-spec.json|

secrets:
  my_secret:
    file: ./my_secret.txt
  my_other_secret:
    external: true
