version: '3'
services:
  redis:
    image: redis:6.2.4
    container_name: rd
    command: redis-server /etc/redis.conf --appendonly yes
    ports:
      - 6379:6379
    user: redis:redis
    hostname: localhost
    volumes:
      - ./data:/data
      - ./redis.conf:/etc/redis.conf
      - ./redis.log:/log/redis.log
