version: "3"
services:
    filebeat:
            image: docker.elastic.co/beats/filebeat:7.9.1
            hostname: filebeat
            container_name: filebeat
            volumes:
            - ./elk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
            - ./elk/filebeat/logs:/usr/share/filebeat/logs
            environment:
            - TZ=Asia/Shanghai