version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mg
    volumes:
      - ./data/mongo/db:/data/db
      - ./data/mongo/log:/data/log
      - ./data/mongo/conf/mongod.conf:/data/mongod.conf
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 27017:27017
    user: mongodb:mongodb
    hostname: localhost
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin