apiVersion: v1
kind: PersistentVolume
metadata:
  name: bit-mykk-pv
spec:
  capacity:
    storage: 100Mi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: bit-kk
  hostPath:
    path: /home/a/workspace/K8S/MQ/Kafka/rd-chart-data
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bit-mykk-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: bit-kk