version: '3'
services:
  zoo1:
    image: zookeeper:3.7.0
    hostname: localhost
    container_name: zk
    user: zookeeper:zookeeper
    ports:
      - 2181:2181
  
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    hostname: localhost
    container_name: kk
    depends_on: 
      - zoo1
    ports:
      - 9092:9092
    environment:
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://121.40.140.178:9092"
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_LOG_DIRS: "/kafka/kafka-logs"
      KAFKA_BROKER_TD: 0
      # KAFKA_CREATE_TOPICS: "arkuser:1:1, arkevent:1:1"
      # KAFKA_TRANSACTION_MAX_TIMEOUT_MS: "7200000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka-logs:/kafka/kafka-logs
