apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\a\software\docker-machine\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-db
  name: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\a\software\docker-machine\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: mysql-db
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_HOST
          value: '%'
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: TZ
          value: Asia/Shanghai
        image: mysql:5.7.34
        imagePullPolicy: ""
        name: mysql
        ports:
        - containerPort: 3306
        resources: {}
      hostname: localhost
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
