version: '3.5'
services:
    rabbitmq:
        image: rabbitmq:3.7.7-management
        restart: always
        container_name: rb
        ports:
          - 5672:5672
          - 15672:15672
        hostname: localhost
        volumes:
          - ./data:/var/lib/rebbitmq
        environment:
            RABBITMQ_DEFAULT_VHOST: my_vhost
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin