version: '3'
services:
  mongodb:
    image: mongo:5.0.0-rc1
    container_name: mg
    hostname: localhost
    user: mongodb:mongodb
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./log:/data/log
      - ./conf/mongod.conf:/data/mongod.conf
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
