version: '3'
services:
  mysql-db:
    container_name: ms
    image: mysql:8.0.25
    restart: always
    hostname: localhost
    ports:
      - 30306:3306
    user: mysql:mysql
    environment:
      MYSQL_ROOT_PASSWORD: root   # root 用户的密码此镜像密码即为root
      MYSQL_ROOT_HOST: "%"           # %
      TZ: Asia/Shanghai
      # MYSQL_USER: a     # 创建一个新用户，这个用户在 `MYSQL_DATABASE` 变量指定的数据库上拥有超级用户权限。
      # MYSQL_PASSWORD: 111111    # 新用户密码
      # MYSQL_DATABASE: db  # 指定一个数据库，在容器启动时创建
      # MYSQL_ALLOW_EMPTY_PASSWORD: false     # 设置为 yes 允许 root 用户的密码为空。（不推荐）
      # MYSQL_RANDOM_ROOT_PASSWORD:  false    # 设置为 yes 将在容器启动时为 root 用户生成一个随机的密码，密码会显示到标准输出流（`GENERATED ROOT PASSWORD:......`）。
      # MYSQL_ONETIME_PASSWORD: false         # 字面意思就是一次性密码，为 root 用户设置，第一次登录后必须修改密码（仅支持 5.6 以上的版本）。
    volumes:
      - ./data:/var/lib/mysql    # MYSQL_DIR=./
      - ./conf:/etc/mysql
      - ./log:/var/log/mysql
      - ./mysql-files:/var/lib/mysql-files/
