version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server /etc/redis.conf --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
      - ./redis.conf:/etc/redis.conf
      - ./redis.log:/log/redis.log
